
networks:
  emsapp:
services:
  emsappdb:
    container_name: app-dp
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 8002:1433
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Password@123#"
    networks:
      - emsapp
  server:
    container_name: server-employee-management-system
    image: ${DOCKER_REGISTRY-}server
    build:
      context: .
      dockerfile: Server/Dockerfile
    ports:
     - 8001:80
    depends_on:
      - emsappdb
    environment:
      - ConnectionStrings__DefaultConnection
    networks:
      - emsapp
  client:
    container_name: client-employee-management-system
    image: ${DOCKER_REGISTRY-}client
    build:
      context: .
      dockerfile: Client/Dockerfile
    ports:
     - 8003:81
    networks:
      - emsapp
  